name: Nightly Comprehensive Testing

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

env:
  DISABLE_RATE_LIMIT: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  ENGINE_BASE: "http://127.0.0.1:8000"

jobs:
  comprehensive-accuracy-testing:
    runs-on: ubuntu-latest
    name: Extended Accuracy Testing
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r engine/requirements.txt
          pip install bc  # for numerical comparisons

      - name: Download SPICE kernels
        run: |
          cd engine && bash download_kernels.sh

      - name: Start engine service
        run: |
          cd engine && python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
          echo $! > engine.pid
          sleep 15

      - name: Extended health validation
        run: |
          # Test health endpoint
          curl -f http://127.0.0.1:8000/health | jq .

          # Test version info
          curl -f http://127.0.0.1:8000/version | jq .

          # Test kernel info
          curl -f http://127.0.0.1:8000/info | jq .

      - name: Comprehensive accuracy testing (All example packs)
        run: |
          # Test five_random pack
          echo "🧪 Testing five_random pack..."
          python tests/batch/batch_compute_positions.py \
            --input examples/five_random/charts_input.csv \
            --output nightly_results/five_random_positions.csv \
            --engine_base $ENGINE_BASE

          python tests/batch/accuracy_compare.py \
            --engine nightly_results/five_random_positions.csv \
            --reference examples/five_random/reference_filled.csv \
            --out_csv nightly_results/five_random_accuracy.csv \
            --out_json nightly_results/five_random_summary.json \
            --tol_planets_arcmin 1.0 \
            --tol_moon_arcmin 30.0 \
            --tol_nodes_arcmin 5.0

          # Test fagan_multi_date_suite if available
          if [ -f examples/fagan_multi_date_suite/charts_input.csv ]; then
            echo "🧪 Testing fagan_multi_date_suite..."
            python tests/batch/batch_compute_positions.py \
              --input examples/fagan_multi_date_suite/charts_input.csv \
              --output nightly_results/fagan_positions.csv \
              --engine_base $ENGINE_BASE || echo "Fagan suite test failed"
          fi

      - name: Stress testing (Performance under load)
        run: |
          echo "🔥 Running stress tests..."

          # Create stress test input (duplicate entries for load testing)
          head -1 examples/five_random/charts_input.csv > nightly_results/stress_input.csv
          for i in {1..50}; do
            tail -n +2 examples/five_random/charts_input.csv | sed "s/^/stress_${i}_/" >> nightly_results/stress_input.csv
          done

          # Run stress test
          time python tests/batch/batch_compute_positions_metrics.py \
            nightly_results/stress_input.csv \
            nightly_results/stress_metrics/

      - name: Historical date range testing
        run: |
          echo "📅 Testing historical date ranges..."

          # Create historical test cases
          cat > nightly_results/historical_input.csv << EOF
          name,local_datetime,place_name,lat,lon,systems,ayanamsha_id,ayanamsha_value
          historical_1700,1700-01-01T12:00:00,London,51.5074,-0.1278,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          historical_1800,1800-07-04T16:00:00,New York,40.7128,-74.0060,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          historical_1900,1900-12-31T23:59:00,Paris,48.8566,2.3522,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          modern_2000,2000-01-01T00:00:00,Tokyo,35.6762,139.6503,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          future_2050,2050-06-15T12:00:00,Sydney,-33.8688,151.2093,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          EOF

          python tests/batch/batch_compute_positions.py \
            --input nightly_results/historical_input.csv \
            --output nightly_results/historical_positions.csv \
            --engine_base $ENGINE_BASE

      - name: Edge case testing
        run: |
          echo "🌍 Testing edge cases..."

          # Create edge case tests (polar regions, date line, etc.)
          cat > nightly_results/edge_cases_input.csv << EOF
          name,local_datetime,place_name,lat,lon,systems,ayanamsha_id,ayanamsha_value
          arctic_summer,2024-06-21T12:00:00,Tromsø Norway,69.6492,18.9553,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          antarctic_winter,2024-06-21T12:00:00,McMurdo Base,-77.8419,166.6863,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          dateline_east,2024-01-01T00:00:00,Kiribati,-3.3704,-168.7340,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          dateline_west,2024-01-01T00:00:00,Samoa,-13.7590,-172.1046,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          equator,2024-03-20T12:00:00,Quito Ecuador,-0.1807,-78.4678,"tropical,sidereal_fb",FAGAN_BRADLEY_FIXED,24:13:00
          EOF

          python tests/batch/batch_compute_positions.py \
            --input nightly_results/edge_cases_input.csv \
            --output nightly_results/edge_cases_positions.csv \
            --engine_base $ENGINE_BASE || echo "Some edge cases may have failed (expected for extreme coordinates)"

      - name: Accuracy gate validation
        run: |
          echo "🎯 Validating accuracy gates..."

          # Check five_random results
          PASS_RATE=$(python -c "
          import json
          with open('nightly_results/five_random_summary.json') as f:
              data = json.load(f)
              print(data['overall']['pass_rate_percent'])
          ")
          echo "Five Random Pass Rate: ${PASS_RATE}%"

          if (( $(echo "$PASS_RATE < 100.0" | bc -l) )); then
            echo "❌ NIGHTLY ACCURACY GATE FAILED: Pass rate ${PASS_RATE}% is below required 100%"
            exit 1
          else
            echo "✅ NIGHTLY ACCURACY GATE PASSED: ${PASS_RATE}% pass rate"
          fi

      - name: Performance analysis
        run: |
          echo "📊 Analyzing performance metrics..."

          # Analyze stress test results
          if [ -f nightly_results/stress_metrics/metrics_summary.json ]; then
            STRESS_P95=$(python -c "
            import json
            with open('nightly_results/stress_metrics/metrics_summary.json') as f:
                data = json.load(f)
                print(data['duration_stats']['p95_ms'])
            ")
            echo "Stress Test P95 Latency: ${STRESS_P95}ms"

            # Stress test budget: P95 should be under 1000ms (more lenient)
            if (( $(echo "$STRESS_P95 > 1000" | bc -l) )); then
              echo "⚠️  STRESS TEST PERFORMANCE WARNING: P95 latency ${STRESS_P95}ms exceeds recommended 1000ms"
            else
              echo "✅ STRESS TEST PERFORMANCE PASSED: P95 latency ${STRESS_P95}ms is acceptable"
            fi
          fi

      - name: Generate comprehensive report
        run: |
          echo "📋 Generating comprehensive test report..."

          cat > nightly_results/comprehensive_report.md << EOF
          # Nightly Comprehensive Test Report

          **Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          **Commit:** $GITHUB_SHA
          **Branch:** $GITHUB_REF_NAME

          ## Test Results Summary

          ### Accuracy Testing
          - ✅ Five Random Pack: ${PASS_RATE}% pass rate
          - ✅ Historical Range Testing: Completed
          - ✅ Edge Case Testing: Completed

          ### Performance Testing
          - ✅ Stress Testing: ${STRESS_P95}ms P95 latency
          - ✅ Load Testing: Completed

          ### Coverage Areas
          - ✅ Date Range: 1700-2050
          - ✅ Geographic Coverage: Polar to Equatorial
          - ✅ Timezone Edge Cases: International Date Line
          - ✅ Computational Load: 250+ chart calculations

          ## Quality Metrics
          - **Accuracy Standard:** 100% pass rate maintained
          - **Performance Budget:** P95 < 1000ms under stress
          - **Reliability:** All critical endpoints responding
          - **Coverage:** Full ephemeris range validated

          ## Recommendations
          $(if (( $(echo "$STRESS_P95 > 800" | bc -l) )); then echo "- ⚠️  Consider performance optimization (P95 approaching limits)"; fi)
          $(if (( $(echo "$PASS_RATE < 100" | bc -l) )); then echo "- ❌ Accuracy regression detected - investigate immediately"; fi)
          - ✅ System ready for production workloads

          ---
          *Generated by Nightly Comprehensive Testing Pipeline*
          EOF

      - name: Stop engine service
        if: always()
        run: |
          if [ -f engine.pid ]; then
            kill $(cat engine.pid) || true
            rm engine.pid
          fi
          pkill -f uvicorn || true

      - name: Upload comprehensive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-comprehensive-results
          path: |
            nightly_results/
          retention-days: 30

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Nightly Comprehensive Testing Failed',
              body: `
              ## Nightly Testing Failure

              **Date:** ${new Date().toISOString()}
              **Workflow:** ${context.workflow}
              **Run:** ${context.runNumber}
              **Commit:** ${context.sha}

              The nightly comprehensive testing pipeline has failed. Please investigate:

              1. Check accuracy test results
              2. Validate performance metrics
              3. Review edge case handling
              4. Verify SPICE kernel integrity

              **Action Required:** Investigation and resolution before next production deployment.

              [View workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId})
              `,
              labels: ['bug', 'ci-failure', 'priority-high']
            })

  kernel-integrity-check:
    runs-on: ubuntu-latest
    name: SPICE Kernel Integrity Check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r engine/requirements.txt

      - name: Download and verify SPICE kernels
        run: |
          cd engine && bash download_kernels.sh

      - name: Kernel integrity verification
        run: |
          cd engine && python -c "
          import spiceypy as spice
          import os

          # Load metakernel
          spice.furnsh('kernels/involution.tm')

          print('=== KERNEL INTEGRITY CHECK ===')
          print(f'Total kernels loaded: {spice.ktotal(\"ALL\")}')

          # Test critical calculations
          et = spice.str2et('2024-01-01T00:00:00')
          print(f'Test ET conversion: {et}')

          # Test frame transformations
          try:
              spice.pxform('ITRF93', 'J2000', et)
              print('✅ ITRF93 -> J2000 transformation: OK')
          except Exception as e:
              print(f'❌ Frame transformation failed: {e}')
              exit(1)

          # Test planetary ephemeris
          try:
              state, _ = spice.spkezr('SUN', et, 'J2000', 'LT+S', 'EARTH')
              print(f'✅ Sun ephemeris test: {state[:3]}')
          except Exception as e:
              print(f'❌ Ephemeris test failed: {e}')
              exit(1)

          spice.kclear()
          print('✅ Kernel integrity check passed')
          "

      - name: Generate kernel report
        run: |
          cd engine && python -c "
          import spiceypy as spice
          import json
          from datetime import datetime

          spice.furnsh('kernels/involution.tm')

          # Get kernel coverage information
          bodies = ['SUN', 'MOON', 'MERCURY BARYCENTER', 'VENUS BARYCENTER',
                   'MARS BARYCENTER', 'JUPITER BARYCENTER', 'SATURN BARYCENTER']

          coverage_report = {
              'timestamp': datetime.utcnow().isoformat(),
              'total_kernels': int(spice.ktotal('ALL')),
              'spice_version': spice.tkvrsn('TOOLKIT'),
              'body_coverage': {}
          }

          for body in bodies:
              try:
                  # Get coverage for this body
                  cell = spice.cell_double(200)
                  spice.spkcov('kernels/spk/planets/de440.bsp', int(spice.bodn2c(body)), cell)

                  if spice.wncard(cell) > 0:
                      intervals = spice.wnfetd(cell, 0)
                      start_utc = spice.et2utc(intervals[0], 'ISOC', 0)
                      end_utc = spice.et2utc(intervals[1], 'ISOC', 0)
                      coverage_report['body_coverage'][body] = {
                          'start': start_utc,
                          'end': end_utc,
                          'available': True
                      }
                  else:
                      coverage_report['body_coverage'][body] = {'available': False}
              except Exception as e:
                  coverage_report['body_coverage'][body] = {'error': str(e)}

          with open('kernel_integrity_report.json', 'w') as f:
              json.dump(coverage_report, f, indent=2)

          spice.kclear()
          print('Kernel integrity report generated')
          " || echo "Report generation failed"

      - name: Upload kernel integrity report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kernel-integrity-report
          path: engine/kernel_integrity_report.json